<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <PropertyGroup>
      <Title>Beskar.Markdown</Title>
      <Description>Simple, low-memory, extensible markdown parser and html renderer.</Description>
      <Authors>Marvin Drude</Authors>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageReadmeFile>README.md</PackageReadmeFile>
      <PublishRepositoryUrl>true</PublishRepositoryUrl>
      <RepositoryUrl>https://github.com/MarvinDrude/Beskar.Markdown</RepositoryUrl>
      <IncludeSymbols>true</IncludeSymbols>
      <IncludeSource>true</IncludeSource>
      <EmbedUntrackedSources>true</EmbedUntrackedSources>
      <SymbolPackageFormat>snupkg</SymbolPackageFormat>
      <PackageIcon>logo.png</PackageIcon>
   </PropertyGroup>

   <ItemGroup>
      <None Include="../README.md" Pack="true" PackagePath="\"/>
      <None Include="../Resources/logo.png" Pack="true" PackagePath="\" Visible="false"/>
   </ItemGroup>
   
   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
   </ItemGroup>

</Project>
